# Generated by Django 3.2.7 on 2022-01-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntropyTown1985',
            fields=[
                ('towncode', models.TextField(db_column='TOWNCODE', primary_key=True, serialize=False)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shannon_entropy', models.DecimalField(blank=True, db_column='Shannon_Entropy', decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'entropy_town_1985',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandcoverChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('builtup', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('barren', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cultivated', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('water', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('vegetation', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'landcover_change',
                'managed': False,
            },
        ),
    ]
