# Generated by Django 3.2.7 on 2022-01-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_map', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandcoverChangeRatio',
            fields=[
                ('builtup', models.DecimalField(blank=True, db_column='Builtup', decimal_places=65535, max_digits=65535, null=True)),
                ('barrem', models.DecimalField(blank=True, db_column='Barrem', decimal_places=65535, max_digits=65535, null=True)),
                ('cultivated', models.DecimalField(blank=True, db_column='Cultivated', decimal_places=65535, max_digits=65535, null=True)),
                ('water', models.DecimalField(blank=True, db_column='Water', decimal_places=65535, max_digits=65535, null=True)),
                ('vegetation', models.DecimalField(blank=True, db_column='Vegetation', decimal_places=65535, max_digits=65535, null=True)),
                ('year', models.DecimalField(blank=True, db_column='Year', decimal_places=65535, max_digits=65535, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'landcover_change_ratio',
                'managed': False,
            },
        ),
    ]
