# Generated by Django 3.2.7 on 2022-01-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_map', '0003_landcoverchangeratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntropyTown2000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towncode', models.TextField(db_column='TOWNCODE')),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shannon_entropy', models.DecimalField(blank=True, db_column='Shannon_Entropy', decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'entropy_town_2000',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntropyTown2015',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towncode', models.TextField(db_column='TOWNCODE')),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shannon_entropy', models.DecimalField(blank=True, db_column='Shannon_Entropy', decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'entropy_town_2015',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
