# Generated by Django 3.2.7 on 2022-01-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_map', '0004_auto_20220117_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntropyTown',
            fields=[
                ('towncode', models.TextField(db_column='TOWNCODE', primary_key=True, serialize=False)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shannon_entropy', models.DecimalField(blank=True, db_column='Shannon_Entropy', decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'entropy_town_1985',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EntropyTown1985',
        ),
        migrations.DeleteModel(
            name='EntropyTown2000',
        ),
        migrations.DeleteModel(
            name='EntropyTown2015',
        ),
    ]
