# Generated by Django 3.2.7 on 2022-01-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_map', '0005_auto_20220117_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='AapdeaTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_eng', models.TextField(blank=True, db_column='TOWN_ENG', null=True)),
                ('period', models.TextField(blank=True, db_column='Period', null=True)),
                ('aapdea', models.DecimalField(blank=True, db_column='AAPDEA', decimal_places=65535, max_digits=65535, null=True)),
                ('dist_to_central', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('towncode', models.TextField(blank=True, db_column='TOWNCODE', null=True)),
            ],
            options={
                'db_table': 'AAPDEA_1',
                'managed': False,
            },
        ),
    ]
