# Generated by Django 3.2.7 on 2022-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_map', '0007_populationall'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntropyVillage',
            fields=[
                ('villcode', models.TextField(db_column='TOWNCODE', primary_key=True, serialize=False)),
                ('shannon_entropy', models.DecimalField(blank=True, db_column='Shannon_Entropy', decimal_places=65535, max_digits=65535, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'entropy_village_1985',
                'managed': False,
            },
        ),
    ]
