# Generated by Django 3.2.7 on 2022-01-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('most_map', '0008_entropyvillage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntropyVillage',
        ),
    ]
