# Generated by Django 3.2.7 on 2022-01-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_map', '0010_entropyvillage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.TextField(blank=True, db_column='TOWN_NAME', null=True)),
                ('town_eng', models.TextField(blank=True, db_column='TOWN_ENG', null=True)),
                ('towncode', models.TextField(blank=True, db_column='TOWNCODE', null=True)),
                ('population', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'population_town',
                'managed': False,
            },
        ),
    ]
