# Generated by Django 3.2.7 on 2022-01-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_map', '0011_populationtown'),
    ]

    operations = [
        migrations.CreateModel(
            name='LcrTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towncode', models.TextField(blank=True, db_column='TOWNCODE', null=True)),
                ('town_eng', models.TextField(blank=True, db_column='TOWN_ENG', null=True)),
                ('lcr', models.DecimalField(blank=True, db_column='LCR', decimal_places=65535, max_digits=65535, null=True)),
                ('period', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LCR_town',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LueTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towncode', models.TextField(blank=True, db_column='TOWNCODE', null=True)),
                ('toen_eng', models.TextField(blank=True, db_column='TOEN_ENG', null=True)),
                ('lue', models.DecimalField(blank=True, db_column='LUE', decimal_places=65535, max_digits=65535, null=True)),
                ('period', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LUE_town',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PcrTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towncode', models.TextField(blank=True, db_column='TOWNCODE', null=True)),
                ('town_eng', models.TextField(blank=True, db_column='TOWN_ENG', null=True)),
                ('pcr', models.DecimalField(blank=True, db_column='PCR', decimal_places=65535, max_digits=65535, null=True)),
                ('period', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PCR_town',
                'managed': False,
            },
        ),
    ]
